function sunStorm() {
    if (GetSpellAbilityId() != FourCC('A02Q')) {
        return
    }

    let udg_SunStorm = RectFromCenterSizeBJ(GetUnitLoc(GetTriggerUnit()), 500.00, 500.00)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
    PolledWait(0.20)
    CreateNUnitsAtLoc(1, FourCC("h00M"), GetOwningPlayer(GetTriggerUnit()), GetRandomLocInRect(udg_SunStorm), bj_UNIT_FACING)
    UnitApplyTimedLifeBJ(1.00, FourCC("BTLF"), GetLastCreatedUnit())
    IssueImmediateOrderBJ(GetLastCreatedUnit(), "creepthunderclap")
}

export function initSunStorm() {
    let trigger = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ( trigger, EVENT_PLAYER_UNIT_SPELL_CAST)
    TriggerAddAction( trigger, () => sunStorm())
}